name: Explorer service
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.4
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common
          sudo apt-get install -y libsodium-dev
          sudo apt-add-repository -y ppa:rael-gc/rvm
          sudo apt-get install libpq-dev rvm
          sudo /usr/share/rvm/bin/rvm install "ruby-2.6.4"
      - name: Set up SECP256k1
        run: |
          git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1 && ./autogen.sh && ./configure && make && ./tests && sudo make install && cd ..
      - name: Build and test with Rake
        run: |
          source /usr/share/rvm/scripts/rvm
          sudo /usr/share/rvm/bin/rvm use 2.6.4
          sudo gem install bundler:2.0.1
          sudo bundle update --bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
          bundle exec rails test RAILS_ENV=test
